name: ci

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

concurrency:
  group: auto-empty-commit-main
  cancel-in-progress: false

jobs:
  autogreen:
    if: github.repository == 'justserpapi/web-rendered-html'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Auto commit
        run: |
          git config --local user.name "Anonymous Committer"
          git config --local user.email "anonymous@users.noreply.github.com"
          git pull --ff-only origin main
          git commit --allow-empty -m "chore: auto empty commit at $(date)"
          git push origin HEAD:main
